
sonar.projectKey=crochet-lab-quality
sonar.organization=crochet-lab-quality
sonar.projectName=crochet-quality-lab
sonar.projectVersion=1.0


sonar.sources=backend-node
sonar.tests=backend-node/tests
sonar.sourceEncoding=UTF-8

sonar.cpd.exclusions=backend-node/tests/fixtures/**, backend-node/tests/mocks/**
sonar.exclusions=backend-node/tests/fixtures/**, backend-node/node_modules/**

sonar.python.version=3.12